name: CI

# Events that trigger the workflow
on:
  # Runs on all pushes to branches
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

concurrency:
  # Behavior:
  # - Group all pull requests: latest push cancels previous ones
  # - Group all branches:
  #   - If main/version- branches: run serially
  #   - Else, latest push cancels previous ones
  group: >
    ${{
      (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number)) ||
      (github.event_name == 'push' && format('branch-{0}', github.ref_name)) ||
      ''
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || !(startsWith(github.ref_name, 'version-') || github.ref_name == 'main' || github.ref_name == 'dev') }}

jobs:
  tiles:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        pdk: [sky130A, gf180mcuD, ihp-sg13g2]
        tile_library: [classic, tiny]
        scl: [default]
        include:
          - pdk: gf180mcuD
            tile_library: tiny
            scl: gf180mcu_as_sc_mcu7t3v3
    name: Tiles (${{ matrix.tile_library }}/${{ matrix.pdk }}/${{ matrix.scl }})
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
          derivation: github:mole99/librelane_plugin_fabulous
      - name: Get the tile library hash
        run: |
          echo "TILE_LIBRARY_SHORT_HASH=$(git rev-parse --short HEAD:ip/fabulous-tiles)" >> $GITHUB_ENV
      - name: Cache the tiles
        uses: actions/cache@v5
        id: cache
        with:
          path: ip/fabulous-tiles/tiles
          key: cache-tiles-${{ matrix.tile_library }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.TILE_LIBRARY_SHORT_HASH }}
      - name: Implement the tiles
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ip/fabulous-tiles/; PDK=${{ matrix.pdk }} SCL=${{ matrix.scl }} TILE_LIBRARY=${{ matrix.tile_library }} nix develop --command make all

  fabrics:
    runs-on: ubuntu-24.04
    needs: [tiles]
    strategy:
      matrix:
        pdk: [sky130A, gf180mcuD, ihp-sg13g2]
        fabric: [classic_fabric_10x10, classic_fabric_heichips25, tiny_fabric_5x5]
        scl: [default]
        exclude:
        # Disably classic_fabric_heichips25 for sky130A and gf180mcuD
        - fabric: classic_fabric_heichips25
          pdk: sky130A
        - fabric: classic_fabric_heichips25
          pdk: gf180mcuD
        include:
          - pdk: gf180mcuD
            fabric: tiny_fabric_5x5
            scl: gf180mcu_as_sc_mcu7t3v3
    name: Fabric (${{ matrix.fabric }}/${{ matrix.pdk }}/${{ matrix.scl }})
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
      - name: Get the tile library
        run: |
          echo "TILE_LIBRARY=$(echo "${{ matrix.fabric }}" | cut -d'_' -f1)" >> $GITHUB_ENV
          echo "TILE_LIBRARY_SHORT_HASH=$(git rev-parse --short HEAD:ip/fabulous-tiles)" >> $GITHUB_ENV
      - name: Restore the tiles
        uses: actions/cache/restore@v5
        with:
          path: ip/fabulous-tiles/tiles
          key: cache-tiles-${{ env.TILE_LIBRARY }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.TILE_LIBRARY_SHORT_HASH }}
          fail-on-cache-miss: true
      - name: Stitch the tiles
        run: |
          PDK=${{ matrix.pdk }} SCL=${{ matrix.scl }} nix develop --command make ${{ matrix.fabric }}
      - name: Upload Macro Folder
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.fabric }}_${{ matrix.pdk }}_${{ matrix.scl }}
          path: fabrics/${{ matrix.fabric }}/macro/${{ matrix.pdk }}/
          include-hidden-files: true
      - name: Implement the User Designs
        run: |
          cd user_designs; PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabric }} nix develop --command make all
      - name: Simulate the Fabric (RTL Emulation)
        run: |
          EMULATION=counter PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabric }} nix develop --command bash -c "cd tb; python3 fabric_tb.py"
      - name: Simulate the Fabric (RTL Simulation)
        run: |
          PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabric }} nix develop --command bash -c "cd tb; python3 fabric_tb.py"
